version: "3.8"

services:
  douala-fiesta:
    build: .
    image: douala-fiesta:latest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.douala-fiesta.rule=Host(`festivaldoualafiesta.cm`) || Host(`www.festivaldoualafiesta.cm`)"
      - "traefik.http.routers.douala-fiesta.entrypoints=websecure"
      - "traefik.http.routers.douala-fiesta.tls.certresolver=letsencrypt"
      - "traefik.http.services.douala-fiesta.loadbalancer.server.port=80"
      # Redirection HTTP -> HTTPS
      - "traefik.http.routers.douala-fiesta-http.rule=Host(`festivaldoualafiesta.cm`) || Host(`www.festivaldoualafiesta.cm`)"
      - "traefik.http.routers.douala-fiesta-http.entrypoints=web"
      - "traefik.http.routers.douala-fiesta-http.middlewares=douala-fiesta-redirect"
      - "traefik.http.middlewares.douala-fiesta-redirect.redirectscheme.scheme=https"

networks:
  proxy:
    external: true
    name: proxy
