// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpjnfyppuaurbffhtocw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wam5meXBwdWF1cmJmZmh0b2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzM4MTQsImV4cCI6MjA3MTQ0OTgxNH0.ZelBmEatb9H7DoH4Ky7WCNoWyzPLop8HzfLxzmaKPxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});